name: langfella2
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  menu: ^0.1.4
  flutter_staggered_grid_view: "^0.3.0"
  font_awesome_flutter: ^8.2.0
  flutter_icons: ^0.1.4
  flip_card: ^0.4.1
  flutter_slidable: "^0.4.7"
  sqflite: ^0.11.1
  path_provider: ^0.4.1
  share:
    git:
      url: https://github.com/d-silveira/flutter-share.git
  background_fetch: '^0.3.1'


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true